export const LIST_CITY_REQUEST = "@@CITYREDUCER/LIST_CITY_REQUEST"
export const LIST_CITY_SUCCESS = "@@CITYREDUCER/LIST_CITY_SUCCESS"
export const LIST_CITY_FAIL = "@@CITYREDUCER/LIST_CITY_FAIL"

export const GET_ROOM_BY_CITY_REQUEST = "@@GETROOMBYCITYREDUCER/GET_ROOM_BY_CITY_REQUEST"
export const GET_ROOM_BY_CITY_SUCCESS = "@@GETROOMBYCITYREDUCER/GET_ROOM_BY_CITY_SUCCESS"
export const GET_ROOM_BY_CITY_FAIL = "@@GETROOMBYCITYREDUCER/GET_ROOM_BY_CITY_FAIL"

export const ROOM_DETAIL_REQUEST = "@@ROOMDETAILREDUCER/GET_ROOM_BY_ID_REQUEST"
export const ROOM_DETAIL_SUCCESS = "@@ROOMDETAILREDUCER/GET_ROOM_BY_ID_SUCCESS"
export const ROOM_DETAIL_FAIL = "@@ROOMDETAILREDUCER/GET_ROOM_BY_ID_FAIL"

export const CHECKOUT_REQUEST = "@@CHECKOUTREDUCER/CHECKOUT_REQUEST"
export const CHECKOUT_SUCCESS = "@@CHECKOUTREDUCER/CHECKOUT_SUCCESS"
export const CHECKOUT_FAIL = "@@CHECKOUTREDUCER/CHECKOUT_FAIL"

export const SIGNUP_REQUEST = "@@SIGNUPREDUCER/SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "@@SIGNUPREDUCER/SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "@@SIGNUPREDUCER/SIGNUP_FAIL"

export const LOGIN_REQUEST = "@@LOGINREDUCER/LOGIN_REQUEST"
export const LOGIN_SUCCESS = "@@LOGINREDUCER/LOGIN_SUCCESS"
export const LOGIN_FAIL = "@@LOGINREDUCER/LOGIN_FAIL"

export const HOMELIST_ROOM_REQUEST = "@@HOMELISTROOMREDUCER/HOMELIST_ROOM_REQUEST"
export const HOMELIST_ROOM_SUCCESS = "@@HOMELISTROOMREDUCER/HOMELIST_ROOM_SUCCESS"
export const HOMELIST_ROOM_FAIL = "@@HOMELISTROOMREDUCER/HOMELIST_ROOM_FAIL"

// Auth
export const AUTH_REQUEST = "@@AUTHREDUCER/AUTH_REQUEST"
export const AUTH_SUCCESS = "@@AUTHREDUCER/AUTH_SUCCESS"
export const AUTH_FAIL = "@@AUTHREDUCER/AUTH_FAIL"

export const COMMENTS_REQUEST = "@@COMMENTSREDUCER/COMMENTS_REQUEST"
export const COMMENTS_SUCCESS = "@@COMMENTSREDUCER/COMMENTS_SUCCESS"
export const COMMENTS_FAIL = "@@COMMENTSREDUCER/COMMENTS_FAIL"