export const LIST_CITY_REQUEST = "@@CITYREDUCER/LIST_CITY_REQUEST"
export const LIST_CITY_SUCCESS = "@@CITYREDUCER/LIST_CITY_SUCCESS"
export const LIST_CITY_FAIL = "@@CITYREDUCER/LIST_CITY_FAIL"

export const GET_ROOM_BY_CITY_REQUEST = "@@GETROOMBYCITYREDUCER/GET_ROOM_BY_CITY_REQUEST"
export const GET_ROOM_BY_CITY_SUCCESS = "@@GETROOMBYCITYREDUCER/GET_ROOM_BY_CITY_SUCCESS"
export const GET_ROOM_BY_CITY_FAIL = "@@GETROOMBYCITYREDUCER/GET_ROOM_BY_CITY_FAIL"