export const LIST_CITY_REQUEST = "@@CITYREDUCER/LIST_CITY_REQUEST"
export const LIST_CITY_SUCCESS = "@@CITYREDUCER/LIST_CITY_SUCCESS"
export const LIST_CITY_FAIL = "@@CITYREDUCER/LIST_CITY_FAIL"

export const DELETE_CITY_REQUEST = "@@CITYREDUCER/DELETE_CITY_REQUEST"
export const DELETE_CITY_SUCCESS = "@@CITYREDUCER/DELETE_CITY_SUCCESS"
export const DELETE_CITY_FAIL = "@@CITYREDUCER/DELETE_CITY_FAIL"

export const CHECKOUT_REQUEST = "@@CHECKOUTREDUCER/CHECKOUT_REQUEST"
export const CHECKOUT_SUCCESS = "@@CHECKOUTREDUCER/CHECKOUT_SUCCESS"
export const CHECKOUT_FAIL = "@@CHECKOUTREDUCER/CHECKOUT_FAIL"

export const SIGNUP_REQUEST = "@@SIGNUPREDUCER/SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "@@SIGNUPREDUCER/SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "@@SIGNUPREDUCER/SIGNUP_FAIL"

export const LOGIN_REQUEST = "@@LOGINREDUCER/LOGIN_REQUEST"
export const LOGIN_SUCCESS = "@@LOGINREDUCER/LOGIN_SUCCESS"
export const LOGIN_FAIL = "@@LOGINREDUCER/LOGIN_FAIL"

// Room
export const HOMELIST_ROOM_REQUEST = "@@ROOMREDUCER/HOMELIST_ROOM_REQUEST"
export const HOMELIST_ROOM_SUCCESS = "@@ROOMREDUCER/HOMELIST_ROOM_SUCCESS"
export const HOMELIST_ROOM_FAIL = "@@ROOMREDUCER/HOMELIST_ROOM_FAIL"

export const GET_ROOM_USER_REQUEST = "@@ROOMREDUCER/GET_ROOM_USER_REQUEST"
export const GET_ROOM_USER_SUCCESS = "@@ROOMREDUCER/GET_ROOM_USER_SUCCESS"
export const GET_ROOM_USER_FAIL = "@@ROOMREDUCER/GET_ROOM_USER_FAIL"

export const DELETE_ROOM_USER_REQUEST = "@@ROOMREDUCER/DELETE_ROOM_USER_REQUEST"
export const DELETE_ROOM_USER_SUCCESS = "@@ROOMREDUCER/DELETE_ROOM_USER_SUCCESS"
export const DELETE_ROOM_USER_FAIL = "@@ROOMREDUCER/DELETE_ROOM_USER_FAIL"

export const ROOM_DETAIL_REQUEST = "@@ROOMREDUCER/GET_ROOM_BY_ID_REQUEST"
export const ROOM_DETAIL_SUCCESS = "@@ROOMREDUCER/GET_ROOM_BY_ID_SUCCESS"
export const ROOM_DETAIL_FAIL = "@@ROOMREDUCER/GET_ROOM_BY_ID_FAIL"

export const ROOM_DATA_REQUEST = "@@ROOMREDUCER/ROOM_DATA_REQUEST"
export const ROOM_DATA_SUCCESS = "@@ROOMREDUCER/ROOM_DATA_SUCCESS"
export const ROOM_DATA_FAIL = "@@ROOMREDUCER/ROOM_DATA_FAIL"

export const GET_ROOM_BY_ID_REQUEST = "@@ROOMREDUCER/GET_ROOM_BY_ID_REQUEST"
export const GET_ROOM_BY_ID_SUCCESS = "@@ROOMREDUCER/GET_ROOM_BY_ID_SUCCESS"
export const GET_ROOM_BY_ID_FAIL = "@@ROOMREDUCER/GET_ROOM_BY_ID_FAIL"


// Auth
export const AUTH_REQUEST = "@@AUTHREDUCER/AUTH_REQUEST"
export const AUTH_SUCCESS = "@@AUTHREDUCER/AUTH_SUCCESS"
export const AUTH_FAIL = "@@AUTHREDUCER/AUTH_FAIL"

export const COMMENTS_REQUEST = "@@COMMENTSREDUCER/COMMENTS_REQUEST"
export const COMMENTS_SUCCESS = "@@COMMENTSREDUCER/COMMENTS_SUCCESS"
export const COMMENTS_FAIL = "@@COMMENTSREDUCER/COMMENTS_FAIL"

export const COMMENTS_POST_REQUEST = "@@COMMENTSREDUCER/COMMENTS_POST_REQUEST"
export const COMMENTS_POST_SUCCESS = "@@COMMENTSREDUCER/COMMENTS_POST_SUCCESS"
export const COMMENTS_POST_FAIL = "@@COMMENTSREDUCER/COMMENTS_POST_FAIL"

// User
export const USER_GET_REQUEST = "@@USERREDUCER/USER_GET_REQUEST"
export const USER_GET_SUCCESS = "@@USERREDUCER/USER_GET_SUCCESS"
export const USER_GET_FAIL = "@@USERREDUCER/USER_GET_FAIL"
